"""
hooks_doc.py -- the "Active Hooks" table of unmassk-gitmemory/SKILL.md,
derived from hooks/hooks.json instead of written by hand.

Why this module exists
----------------------
`skills/unmassk-gitmemory/SKILL.md` is loaded on every session start, so any
falsehood in it is a falsehood Claude states to the user with full confidence.
Its hook list was hand-written prose and drifted: it described a per-message
memory-injection hook retired months earlier, named the wrong number of managed
CLAUDE.md blocks, and got the recall whitelist backwards. Correcting the prose
by hand fixes today and guarantees nothing about six months from now.

So the section is split in two, side by side, neither overwriting the other:

- **Derived** -- which hook runs on which event, with which matcher and which
  timeout, and whether the file is actually on disk. All of that is a fact
  about `hooks/hooks.json` and the filesystem, so it is generated between two
  markers (same pattern `lib/managed_blocks.py` uses for CLAUDE.md) and
  regenerated by `bin/hooks_doc_sync.py --write`.
- **Judgment** -- what a hook *means* for the reader, when it will get in the
  way, which of them are known-dead. That cannot be generated and stays
  hand-written, in prose bullets *below* the generated block.

`managed_blocks.upsert_managed_blocks()` is deliberately NOT reused here.
Its block bodies are fixed literals for a different file (CLAUDE.md), and its
one genuinely expensive behaviour -- the orphaned-END repair pinned by issue
#63's T1 tests -- is the opposite of what a generated block wants: with a
marker missing we must refuse and say so, never guess where the block ended
(see `replace_block`). What is reused is the pattern, not a copy of the logic.

Two contracts, both deliberate
------------------------------
- **`parse_hook_declarations()` returns None, never []**, when hooks.json
  cannot be read. `[]` means "this install declares no hooks"; collapsing the
  two is how a check reports green because it is blind (see
  `tests/test_doctor_derived_expectations.py`).
- **`compare_hooks_doc()` fails open.** It answers only about what it could
  actually read. Anything it cannot determine comes back as "cannot verify" or
  as None (does not apply) -- never as an invented verdict.
"""

from __future__ import annotations

import json
import os
import re
import sys

# Loading this module standalone (importlib, without lib/ on sys.path) would
# break the deferred `git_helpers` import inside write_hooks_block(). Same
# self-insertion guard lib/cache_sync_check.py already uses; a no-op under
# normal execution, where the caller has already put lib/ on the path.
_LIB_DIR = os.path.dirname(os.path.abspath(__file__))
if _LIB_DIR not in sys.path:
    sys.path.insert(0, _LIB_DIR)


# ── Config ────────────────────────────────────────────────────────────────

# Short-lived instrumentation: declared in hooks.json only while a measurement
# runs, then retired. A probe must never become a permanent requirement of the
# health check, nor appear in documentation that outlives it.
# Single source of truth -- bin/git-memory-doctor.py imports this name.
TRANSIENT_HOOKS = {"_probe_canal.py"}

# Matches the hook filename inside a hooks.json command line, e.g.
# "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/session-start-boot.py".
HOOK_COMMAND_RE = re.compile(r"hooks/([^/\s]+\.py)")

# The documented skill, relative to the plugin root.
SKILL_REL_PATH = ("skills", "unmassk-gitmemory", "SKILL.md")

BEGIN_MARKER = "<!-- BEGIN unmassk-active-hooks (generated from hooks/hooks.json — do not edit by hand) -->"
END_MARKER = "<!-- END unmassk-active-hooks -->"

# Shown in every "regenerate it" message, so the fix is never a guess.
REGEN_HINT = "regenerate with `bin/hooks_doc_sync.py --write`"

# Appended to a row whose hook file is declared but absent from disk.
MISSING_FILE_MARK = " ⚠️ FILE NOT FOUND"

_TABLE_HEADER = (
    "| Event | Matcher | Hook file | Timeout |\n"
    "|---|---|---|---|"
)

# Column index of the "Hook file" cell once a table row is split on "|".
# A row renders as ["", " Event ", " Matcher ", " Hook ", " Timeout ", ""].
_HOOK_CELL_INDEX = 3

_PY_NAME_RE = re.compile(r"^[^\s`]+\.py$")

# Splits a markdown table row on real cell separators only. A cell may legally
# contain an escaped pipe -- one real matcher is `Write|Edit`, rendered as
# `Write\|Edit` -- and splitting on those too shifts every later column,
# which silently loses the hook filename in that row.
_ROW_SPLIT_RE = re.compile(r"(?<!\\)\|")


# ── Derivation from hooks.json ────────────────────────────────────────────

def _format_timeout(raw: object) -> str:
    """Render a declared timeout, or an em dash when none is declared.

    A bool is an int in Python; `"timeout": true` is malformed input, not a
    zero-second timeout, so it renders as "not declared" like any other
    non-number.
    """
    if isinstance(raw, bool) or not isinstance(raw, (int, float)):
        return "—"
    return f"{raw:g}s"


def _escape_cell(text: str) -> str:
    """Escape a value for a markdown table cell.

    The only character that can break the table is the pipe, and one real
    matcher contains it (`Write|Edit`).
    """
    return text.replace("|", "\\|")


def parse_hook_declarations(plugin_root: str) -> list[dict[str, str]] | None:
    """Read hooks/hooks.json and return one record per declared hook.

    Source of truth is the same file Claude Code reads to decide what to run,
    in declaration order (json.load preserves object order, so successive
    renders of an unchanged hooks.json are byte-identical). Transient probes
    (TRANSIENT_HOOKS) are excluded -- they are instrumentation, not behaviour
    anyone should document.

    Args:
        plugin_root: Directory holding hooks/, lib/, bin/, skills/.

    Returns:
        A list of {"event", "matcher", "hook", "timeout"} dicts (possibly
        empty if hooks.json declares nothing), or None if hooks.json is
        missing, unreadable or not valid JSON. None means "cannot verify" and
        must never be collapsed into an empty list.
    """
    hooks_json = os.path.join(plugin_root, "hooks", "hooks.json")
    try:
        # Plain read on purpose: a read-only lookup of a file the toolkit
        # itself ships, and this project's threat model is the system against
        # itself, not a hostile repo (see CLAUDE.md).
        with open(hooks_json, encoding="utf-8") as f:
            data = json.load(f)
    except (json.JSONDecodeError, OSError, UnicodeDecodeError):
        return None
    if not isinstance(data, dict):
        return None
    events = data.get("hooks")
    if not isinstance(events, dict):
        return None

    records: list[dict[str, str]] = []
    for event, groups in events.items():
        if not isinstance(groups, list):
            continue
        for group in groups:
            if not isinstance(group, dict):
                continue
            entries = group.get("hooks")
            if not isinstance(entries, list):
                continue
            matcher = group.get("matcher")
            for entry in entries:
                if not isinstance(entry, dict):
                    continue
                match = HOOK_COMMAND_RE.search(str(entry.get("command", "")))
                if not match:
                    continue
                name = match.group(1)
                if name in TRANSIENT_HOOKS:
                    continue
                records.append({
                    "event": str(event),
                    "matcher": matcher if isinstance(matcher, str) and matcher else "—",
                    "hook": name,
                    "timeout": _format_timeout(entry.get("timeout")),
                })
    return records


def hook_filenames(plugin_root: str) -> list[str] | None:
    """Sorted, deduplicated hook filenames declared in hooks.json.

    Returns:
        The sorted list, or None when hooks.json cannot be read (the same
        "cannot verify" contract as parse_hook_declarations).
    """
    records = parse_hook_declarations(plugin_root)
    if records is None:
        return None
    return sorted({rec["hook"] for rec in records})


# ── Rendering ─────────────────────────────────────────────────────────────

def render_hooks_block(plugin_root: str, records: list[dict[str, str]]) -> str:
    """Render the generated block body (markers excluded, no outer newlines).

    Args:
        plugin_root: Used to check each declared hook file's presence on disk.
        records: Output of parse_hook_declarations().
    """
    hooks_dir = os.path.join(plugin_root, "hooks")
    lines = [
        f"**{len(records)} hook invocations declared** in `hooks/hooks.json`. "
        "Event, matcher and timeout are read from that file; file presence is "
        "checked on disk; transient measurement probes are excluded. This "
        f"table is generated — {REGEN_HINT}, never by editing it here.",
        "",
        _TABLE_HEADER,
    ]
    for rec in records:
        name = rec["hook"]
        if not os.path.isfile(os.path.join(hooks_dir, name)):
            cell = f"`{name}`{MISSING_FILE_MARK}"
        else:
            cell = f"`{name}`"
        matcher = rec["matcher"]
        matcher_cell = "—" if matcher == "—" else f"`{_escape_cell(matcher)}`"
        lines.append(
            f"| `{_escape_cell(rec['event'])}` | {matcher_cell} "
            f"| {cell} | {rec['timeout']} |"
        )
    return "\n".join(lines)


# ── Block surgery (markers must already exist) ────────────────────────────

def skill_doc_path(plugin_root: str) -> str:
    """Absolute path of the SKILL.md carrying the generated block."""
    return os.path.join(plugin_root, *SKILL_REL_PATH)


def _markers_ok(content: str) -> bool:
    """True when exactly one well-ordered marker pair is present."""
    if content.count(BEGIN_MARKER) != 1 or content.count(END_MARKER) != 1:
        return False
    return content.find(BEGIN_MARKER) < content.find(END_MARKER)


def extract_block(content: str) -> str | None:
    """Return the current block body, or None if the markers are unusable."""
    if not _markers_ok(content):
        return None
    start = content.find(BEGIN_MARKER) + len(BEGIN_MARKER)
    return content[start:content.find(END_MARKER)].strip()


def replace_block(content: str, body: str) -> str | None:
    """Return `content` with the block body replaced by `body`.

    Refuses (returns None) unless exactly one BEGIN and one END marker exist,
    in that order. A dangling BEGIN gives no reliable signal of where the
    block ends, and inventing a boundary risks eating the hand-written prose
    that lives right below it -- the exact failure issue #63 paid for in
    CLAUDE.md. Refusing is the only safe answer; the caller reports it.
    """
    if not _markers_ok(content):
        return None
    start = content.find(BEGIN_MARKER)
    end = content.find(END_MARKER)
    return f"{content[:start]}{BEGIN_MARKER}\n{body}\n{content[end:]}"


def _documented_hooks(block_body: str) -> set[str]:
    """Hook filenames the generated block currently claims exist.

    Only table rows are read -- the block's own prose mentions
    `bin/hooks_doc_sync.py`, and a naive scan for "*.py" would report that as
    a documented hook and then as a phantom one.
    """
    names: set[str] = set()
    for line in block_body.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cells = _ROW_SPLIT_RE.split(line)
        if len(cells) <= _HOOK_CELL_INDEX:
            continue
        cell = cells[_HOOK_CELL_INDEX].strip().strip("`")
        # Strip anything appended after the code span (e.g. the missing-file
        # mark) before testing the shape.
        cell = cell.split("`")[0].strip()
        if _PY_NAME_RE.match(cell):
            names.add(cell)
    return names


# ── The two public verbs ──────────────────────────────────────────────────

def compare_hooks_doc(plugin_root: str) -> tuple[str, str] | None:
    """Compare the generated block in SKILL.md against hooks.json right now.

    Severity is not uniform, because the two directions of drift are not the
    same failure:

    - **A hook documented that hooks.json no longer declares -> error.** This
      is the one that makes Claude assert a falsehood: it reads the section
      every session and tells the user a behaviour exists that nothing will
      ever produce. It is also unreachable by any legitimate half-finished
      state -- removing a hook and leaving its row behind is precisely what
      must be blocked.
    - **A declared hook absent from the table -> warning.** The doc is
      incomplete, but everything it says is still true: Claude under-informs
      rather than misinforms. Erroring here would also turn the report red on
      the normal transient state of having just added a hook.
    - **Same hooks, different event/matcher/timeout/presence -> warning.**
      Wrong metadata about a hook that does exist is a smaller lie with a
      smaller blast radius than a hook that does not exist at all.

    Returns:
        (level, message) with level in {"ok", "warn", "error"}, or None when
        the check does not apply -- hooks.json underivable (the doctor's Hooks
        check already reports that, and saying it twice is noise) or SKILL.md
        absent (its Skills check owns that).
    """
    records = parse_hook_declarations(plugin_root)
    if not records:
        return None

    path = skill_doc_path(plugin_root)
    if not os.path.isfile(path):
        return None
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except (OSError, UnicodeDecodeError):
        # Fail open: unreadable is not a verdict about the content.
        return ("warn", "cannot verify — SKILL.md could not be read")

    current = extract_block(content)
    if current is None:
        return ("warn",
                f"cannot verify — generated block markers missing from SKILL.md ({REGEN_HINT})")

    expected = render_hooks_block(plugin_root, records)
    if current == expected.strip():
        return ("ok", f"SKILL.md documents the {len(records)} declared hook invocations")

    declared = {rec["hook"] for rec in records}
    documented = _documented_hooks(current)
    phantom = sorted(documented - declared)
    if phantom:
        return ("error",
                f"SKILL.md documents {len(phantom)} hook(s) hooks.json no longer "
                f"declares: {', '.join(phantom)} — Claude states this as fact "
                f"every session ({REGEN_HINT})")
    absent = sorted(declared - documented)
    if absent:
        return ("warn",
                f"SKILL.md does not document {len(absent)} declared hook(s): "
                f"{', '.join(absent)} ({REGEN_HINT})")
    return ("warn",
            "SKILL.md hook table is stale — same hooks, but event, matcher, "
            f"timeout or file presence differs from hooks.json ({REGEN_HINT})")


def write_hooks_block(plugin_root: str) -> tuple[str, str]:
    """Regenerate the block in SKILL.md from hooks.json.

    Returns:
        (status, message) with status in {"written", "unchanged", "failed"}.
        "failed" is always accompanied by the concrete reason; nothing is
        written on any failure path.
    """
    records = parse_hook_declarations(plugin_root)
    if records is None:
        return ("failed", "hooks/hooks.json is missing, unreadable or not valid JSON")
    if not records:
        return ("failed", "hooks/hooks.json declares no hooks")

    path = skill_doc_path(plugin_root)
    try:
        with open(path, encoding="utf-8") as f:
            content = f.read()
    except (OSError, UnicodeDecodeError) as exc:
        return ("failed", f"cannot read {path}: {exc}")

    updated = replace_block(content, render_hooks_block(plugin_root, records))
    if updated is None:
        return ("failed",
                f"{path} does not contain exactly one {BEGIN_MARKER!r} ... "
                f"{END_MARKER!r} pair, in that order — refusing to guess where "
                "the block starts or ends")
    if updated == content:
        return ("unchanged", f"{len(records)} hook invocations, already in sync")

    # Deferred import: tests/test_migrate_statusline.py stubs
    # sys.modules["git_helpers"] with a minimal fake, and this module is
    # imported at module level by bin/git-memory-doctor.py. Keeping the import
    # inside the one function that needs it means loading hooks_doc never
    # depends on git_helpers being the real module.
    from git_helpers import open_no_follow_symlink

    # atomic=True: a full-content rewrite with a bare "w" truncates on the
    # spot, so a crash mid-write would leave SKILL.md empty or half-written --
    # the same reason CLAUDE.md's managed-block writers use it.
    with open_no_follow_symlink(path, "w", atomic=True) as f:
        f.write(updated)
    return ("written", f"{len(records)} hook invocations written to {path}")
